# Generated by Django 2.1.7 on 2019-03-12 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authenticator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticator',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 22, 46, 46, 769659, tzinfo=utc)),
        ),
    ]
