# Generated by Django 2.1.7 on 2019-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='hello', max_length=120),
            preserve_default=False,
        ),
    ]
